### ISSUE TITLE
Feature Request: float32 serialization

### ISSUE THREAD

**Issue by pllim** [jbcurtin/bert-etl#11]
Please support JSON serialization for `np.float32` data type. Thanks!

**Comment by jbcurtin** [comment]
Shipped support today,
https://bert-etl.readthedocs.io/en/latest/queue_encoders__and__queue_decoders.html

**Comment by pllim** [comment]
As discussed offline, this support is also necessary for the `redis` version.

**Comment by pllim** [comment]
I think you said this is fixed.
