### ISSUE TITLE
Question: How to pass test event to test Lambda after deployment?

### ISSUE THREAD

**Issue by pllim** [jbcurtin/bert-etl#14]
I think we talked about this, but it is still unclear to me how I can send `event` straight to the deployed Lambda via the test interface after deployment. Thanks!

More specifically, how does my function access the `event` from the handler?

**Comment by pllim** [comment]
Wait... It automagicallly goes into the `work_queue`?

**Comment by pllim** [comment]
Nope. Doesn't seem like it.

**Comment by jbcurtin** [comment]
It automatically goes into the `work_queue` when `DEBUG=True`. This prevents the lambda function from proc'ing the entire stream of lambda functions

**Comment by pllim** [comment]
Superseded by #16
