### ISSUE TITLE
Feature Request: DEBUG that allows streaming?

### ISSUE THREAD

**Issue by pllim** [jbcurtin/bert-etl#16]
If this is too crazy, let me know. But I am envisioning a use case where the first function (the `noop` one) would get triggered manually by a test event via the dashboard. But then it proceeds to cascade the call to the rest of the "worker" functions.

Currently, `DEBUG="true"` enables the manual trigger but also disables the streaming (DynamoDB).

Should I be using `bert-deploy.py -m bert_tutorial -i bert_tutorial/test-event.json` instead? Or is that also limited by the DEBUG behavior above?

**Comment by jbcurtin** [comment]
bert-etl support is limited
