### ISSUE TITLE
Feature Request: Report back total run time

### ISSUE THREAD

**Issue by pllim** [jbcurtin/bert-etl#19]
Let's say I fire off the "main" AWS Lambda function that calls other functions concurrently. When they are all done end-to-end, would be nice to know in an easier way (without have to manually scrap through the CloudWatch logs):

* Combined run time for all of them (CPU time).
* Run time from start to finish without counting those running in parallel (wall time).

**Comment by jbcurtin** [comment]
bert-etl support is limited
