### ISSUE TITLE
Feature Request: User doc on RTD

### ISSUE THREAD

**Issue by pllim** [jbcurtin/bert-etl#2]
Would be nice to have:

1. User facing documentation, with design diagrams maybe.
2. Build documentation on ReadTheDocs.

cc @mustaric

**Comment by jbcurtin** [comment]
https://bert-etl.readthedocs.io/en/latest/

**Comment by pllim** [comment]
Thanks! I think the RTD setup satisfies point 2, but the content is still pretty bare.
