### ISSUE TITLE
Feature Request: Let Lambda functions be testable on AWS

### ISSUE THREAD

**Issue by pllim** [jbcurtin/bert-etl#3]
Once deployed to AWS, would be nice to be able to invoke Lambda on AWS with given test cases. Something like "invoke the Lambda function" section in https://docs.aws.amazon.com/lambda/latest/dg/getting-started-create-function.html

**Comment by jbcurtin** [comment]
When `DEBUG == True`, functions maybe tested from the AWS Lambda Console. When setting `DEBUG==False` in `bert-etl.yaml`-`enviornment`, the function will enable Dynamodb Streams and the full application maybe tested.
