### ISSUE TITLE
Question: Can I not hardcode function name?

### ISSUE THREAD

**Issue by pllim** [jbcurtin/bert-etl#5]
Currently:

```python
@binding.follow('noop')
def funcname():
    work_queue, done_queue, ologger = utils.comm_binders(funcname)
```

Will this work in your framework? Can I use this instead?

```python
@binding.follow('noop')
def funcname():
    import sys
    work_queue, done_queue, ologger = utils.comm_binders(sys._getframe().f_code.co_name)
```

ref: https://stackoverflow.com/questions/5067604/determine-function-name-from-within-that-function-without-using-traceback

**Comment by pllim** [comment]
Answer: Yes.

**Comment by jbcurtin** [comment]
Looks like `sys._getframe().f_code.co_name` returns a string, it'll work but not as intended. 🤔 `comm_bindings` needs the function itself. Let me think about this a little bit?

**Comment by pllim** [comment]
Ah, it's okay if this is not trivial. We can just close as "won't fix". Not worth spending much time over.

**Comment by jbcurtin** [comment]
its definitely something I'd like to investigate more. Every now and again, I cross the function names and it ends up creating a nasty bug that is hard to track down. It'll be a good interface improvement for the API
